MANOR.API/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using MANOR.API.Areas.HelpPage.ModelDescriptions;
using MANOR.API.Areas.HelpPage.Models;

namespace MANOR.API.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        private const string ErrorViewName = "Error";

        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View(ErrorViewName);
        }

        public ActionResult ResourceModel(string modelName)
        {
            if (!String.IsNullOrEmpty(modelName))
            {
                ModelDescriptionGenerator modelDescriptionGenerator = Configuration.GetModelDescriptionGenerator();
                ModelDescription modelDescription;
                if (modelDescriptionGenerator.GeneratedModels.TryGetValue(modelName, out modelDescription))
                {
                    return View(modelDescription);
                }
            }

            return View(ErrorViewName);
        }
    }
}

MANOR.API/Controllers/VisualizedataController.cs
using MANOR.Infrastructure.Interfaces;
using System.Linq;
using System.Text;
using System.Web.Mvc;

namespace MANOR.API.Controllers
{
    public class VisualizedataController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public VisualizedataController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        // GET: Visualizedata
        public ActionResult Visuallize()
        {
            GenerateChartData();

            return View();
        }

        private void GenerateChartData()
        {
            var dataSource =
                _unitOfWork.TelemetryRepository.ListOfAllTelemetries.OrderBy(x => x.Car.Chassis).GroupBy(x => x.Lap.Number);

            StringBuilder strScript = new StringBuilder();

            var mainstrings = new StringBuilder();

            foreach (var data in dataSource)
            {
                var innerstrings = new StringBuilder();

                innerstrings.Append("['" + "Lap " + data.Key + "',");

                int count = 0;
                double sum = 0;

                foreach (var x in data)
                {
                    sum += x.Car.TyreTemp;
                    innerstrings.Append(x.Car.TyreTemp + ",");

                    count++;
                }

                if (count == 1)
                {
                    innerstrings.Append(0 + ",");
                }

                innerstrings.Append((double)sum / count + "],");

                mainstrings.Append(innerstrings);
                count = 0;
                sum = 0;
            }

            mainstrings.Remove(mainstrings.Length - 1, 1);
            strScript.Append(mainstrings).Append("]);");



            string final = strScript.ToString();

            ViewBag.chartstring = final;
        }
    }
}

MANOR.API/Views/Shared/_Layout.cshtml
@using System
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MANOR RACING", "Compare", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Compare", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Visualize", "Visuallize", "Visualizedata", new { area = "" }, null)</li>
                    <li><a href="/swagger">Swagger</a></li>
                    <li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")

    @Scripts.Render("~/bundles/bootstrap")

    @RenderSection("scripts", required: false)

</body>
</html>

MANOR.API/Views/Shared/_lapcomparison.cshtml
@using System
@model MANOR.API.ViewModels.LapViewModel
@{

    var tel1 = @Model.LapModel[0];
    var tel2 = @Model.LapModel[1];
    var ch1 = tel1.Car;
    var ch2 = tel2.Car;
}

<div class="chassis-box">
    <div class="text-left">
        <p><span class="text-info"><b>Time:</b></span>@tel1.Lap.Timespan</p>
        <p><span class="text-info"><b>Chasis:</b></span>@ch1.Chassis</p>
        <p><span class="text-info"><b>Tyre Tempature:</b></span> @string.Format("{0}\u00B0C", ch1.TyreTemp)</p>
        <p><span class="text-info"><b>Fuel:</b></span> @ch1.Fuel</p>
        <p><span class="text-info"><b>Weight:</b></span>@ch1.Weight</p>
    </div>
</div>
<div class="chassis-box">
    <div class="text-left">
        <p><span class="text-info"><b>Time:</b></span>@tel2.Lap.Timespan</p>
        <p><span class="text-info"><b>Chasis:</b></span>@ch2.Chassis</p>
        <p><span class="text-info"><b>Tyre Tempature:</b></span>@string.Format("{0}\u00B0C", ch2.TyreTemp)</p>
        <p><span class="text-info"><b>Fuel:</b></span> @ch2.Fuel</p>
        <p><span class="text-info"><b>Weight:</b></span>@ch2.Weight</p>
    </div>
</div>

<div>
    <div class="text-center panel panel-primary">
        <div class="panel-heading">Lap time/ fuel burn Deltas</div>
        <div class="panel-body">
            <p><span class="text-info"><b>Detla time: </b></span>@(tel1.Lap.Timespan.Subtract(tel2.Lap.Timespan).Duration())</p>
            <p><span class="text-info"><b>Delta fuel Burn:</b></span>@Math.Abs(ch1.Fuel - ch2.Fuel)</p>
        </div>
    </div>
</div>